from pathlib import Path


def r(text, old, new, label):
    if old not in text:
        raise SystemExit(f"anchor not found: {label}")
    return text.replace(old, new, 1)

p = Path("custom_components/ev_planner/core/planner.py")
s = p.read_text()
s = r(s, "CURRENT_TIEBREAK_EPSILON = 0.000000001\n", "CURRENT_TIEBREAK_EPSILON = 0.000000001\n\nPLANNER_MODE_NORMAL = \"Normaal laden\"\nPLANNER_MODE_SOLAR_ONLY = \"Alleen zonneladen\"\nPV_ROUNDING_DOWN = \"Naar beneden — geen netenergie\"\nPV_ROUNDING_UP = \"Naar boven — kleine netaanvulling toegestaan\"\n", "constants")
s = r(s, "        max_phase_switches: int = 2,\n    ) -> None:\n", "        max_phase_switches: int = 2,\n        planner_mode: str = PLANNER_MODE_NORMAL,\n        pv_rounding: str = PV_ROUNDING_DOWN,\n    ) -> None:\n", "settings signature")
s = r(s, "        self.max_phase_switches = int(\n            max_phase_switches\n        )\n\n        self._validate()\n", "        self.max_phase_switches = int(\n            max_phase_switches\n        )\n\n        self.planner_mode = str(planner_mode)\n        self.pv_rounding = str(pv_rounding)\n\n        self._validate()\n", "settings fields")
s = r(s, "        if self.max_phase_switches < 0:\n\n            raise ValueError(\n                \"max_phase_switches mag niet negatief zijn.\"\n            )\n\n\n##############################################################################\n# ChargingDecision\n", "        if self.max_phase_switches < 0:\n\n            raise ValueError(\n                \"max_phase_switches mag niet negatief zijn.\"\n            )\n\n        if self.planner_mode not in (PLANNER_MODE_NORMAL, PLANNER_MODE_SOLAR_ONLY):\n            raise ValueError(f\"Ongeldige planner_mode: {self.planner_mode}\")\n\n        if self.pv_rounding not in (PV_ROUNDING_DOWN, PV_ROUNDING_UP):\n            raise ValueError(f\"Ongeldige pv_rounding: {self.pv_rounding}\")\n\n\n##############################################################################\n# ChargingDecision\n", "settings validation")
s = r(s, "            hour.pv_estimate = float(\n                solar_hour.pv_estimate\n            )\n\n            hour.pv_estimate10 = float(\n", "            hour.pv_estimate = float(\n                solar_hour.pv_estimate\n            )\n            hour.pv_source_duration = (solar_hour.end - solar_hour.start).total_seconds() / 3600.0\n\n            hour.pv_estimate10 = float(\n", "source duration")
s = r(s, "            partial_hour.pv_estimate = float(\n                source_hour.pv_estimate\n            )\n\n            partial_hour.pv_estimate10 = float(\n", "            partial_hour.pv_estimate = float(\n                source_hour.pv_estimate\n            )\n            partial_hour.pv_source_duration = float(\n                getattr(\n                    source_hour,\n                    \"pv_source_duration\",\n                    (source_hour.end - source_hour.start).total_seconds() / 3600.0,\n                )\n            )\n\n            partial_hour.pv_estimate10 = float(\n", "partial source duration")
s = r(s, "            if pv < float(\n                self.settings.min_pv_kwh\n            ):\n\n                pv = 0.0\n", "            if (\n                self.settings.planner_mode == PLANNER_MODE_SOLAR_ONLY\n                and pv < float(self.settings.min_pv_kwh)\n            ):\n                pv = 0.0\n", "available PV threshold")
old = '''    def _pv_rate_kw(\n        self,\n        hour: Hour,\n    ) -> float:\n        \"\"\"\n        Zonne-opwek van dit uur, als constant vermogen (kW) over de\n        volledige beschikbare duur van dit uur -- de basis voor de\n        \"gelijkmatig uitgesmeerd\"-aanname.\n        \"\"\"\n\n        duration = self._hour_duration(\n            hour\n        )\n\n        if duration <= 0:\n\n            return 0.0\n\n        pv = float(\n            hour.pv_estimate\n        )\n\n        if pv < 0:\n\n            pv = 0.0\n\n        if pv < float(\n            self.settings.min_pv_kwh\n        ):\n\n            pv = 0.0\n\n        return float(\n            pv / duration\n        )\n\n'''
new = '''    def _pv_rate_kw(\n        self,\n        hour: Hour,\n    ) -> float:\n        \"\"\"Gemiddeld PV-vermogen over het oorspronkelijke Solcast-uur.\"\"\"\n        duration = self._hour_duration(hour)\n        if duration <= 0:\n            return 0.0\n        pv = max(0.0, float(hour.pv_estimate))\n        if (\n            self.settings.planner_mode == PLANNER_MODE_SOLAR_ONLY\n            and pv < float(self.settings.min_pv_kwh)\n        ):\n            pv = 0.0\n        source_duration = float(getattr(hour, \"pv_source_duration\", duration))\n        if source_duration <= 0:\n            return 0.0\n        return float(pv / source_duration)\n\n    def _solar_only_current_for_pv(self, pv_rate_kw: float, phases: int):\n        if pv_rate_kw <= 0:\n            return None\n        power_per_amp = VOLTAGE_V * float(phases) / 1000.0\n        if power_per_amp <= 0:\n            return None\n        current_float = pv_rate_kw / power_per_amp\n        if current_float < MIN_CHARGE_CURRENT_A:\n            return None\n        if self.settings.pv_rounding == PV_ROUNDING_UP:\n            current_a = int(math.ceil(current_float - 1e-9))\n        else:\n            current_a = int(math.floor(current_float + 1e-9))\n        if current_a < MIN_CHARGE_CURRENT_A:\n            return None\n        return min(current_a, MAX_CHARGE_CURRENT_A)\n\n'''
s = r(s, old, new, "PV rate")
s = r(s, "        max_price = float(\n            self.settings.max_price\n        )\n\n        ######################################################################\n        # Per uur, per fase: beschikbare duur, zonvermogen, geldige\n", "        max_price = float(\n            self.settings.max_price\n        )\n        solar_only = self.settings.planner_mode == PLANNER_MODE_SOLAR_ONLY\n\n        ######################################################################\n        # Per uur, per fase: beschikbare duur, zonvermogen, geldige\n", "mode")
s = r(s, "                    for current_a in valid_currents_by_phase[\n                        phase\n                    ]:\n\n                        power = self._actual_power_for_current(\n", "                    candidate_currents = valid_currents_by_phase[phase]\n\n                    if solar_only:\n                        solar_current = self._solar_only_current_for_pv(pv_rates[index], phase)\n                        candidate_currents = [] if solar_current is None else [solar_current]\n\n                    for current_a in candidate_currents:\n\n                        power = self._actual_power_for_current(\n", "full candidates")
s = r(s, "                        if (\n                            prices[index] > max_price\n                            and paid > 0.000001\n                        ):\n", "                        if (\n                            not solar_only\n                            and prices[index] > max_price\n                            and paid > 0.000001\n                        ):\n", "full price")
s = r(s, "                            new_cost = (\n                                cost\n                                + paid\n                                * prices[index]\n                                - CURRENT_TIEBREAK_EPSILON\n                                * current_a\n                            )\n", "                            if solar_only:\n                                new_cost = cost + paid - CURRENT_TIEBREAK_EPSILON * current_a\n                            else:\n                                new_cost = (\n                                    cost\n                                    + paid * prices[index]\n                                    - CURRENT_TIEBREAK_EPSILON * current_a\n                                )\n", "full objective")
s = r(s, "                        price_ok_currents = (\n                            valid_currents_by_phase[\n                                phase\n                            ]\n                        )\n\n                        best_current = None\n", "                        price_ok_currents = valid_currents_by_phase[phase]\n\n                        if solar_only:\n                            solar_current = self._solar_only_current_for_pv(pv_rate, phase)\n                            price_ok_currents = [] if solar_current is None else [solar_current]\n\n                        best_current = None\n", "finish candidates")
s = r(s, "                            if (\n                                prices[index]\n                                > max_price\n                                and power\n                                > pv_rate + 0.000001\n                            ):\n", "                            if (\n                                not solar_only\n                                and prices[index] > max_price\n                                and power > pv_rate + 0.000001\n                            ):\n", "finish price")
s = r(s, "                        new_cost = (\n                            cost\n                            + finish_paid\n                            * prices[index]\n                        )\n", "                        if solar_only:\n                            new_cost = cost + finish_paid\n                        else:\n                            new_cost = cost + finish_paid * prices[index]\n", "finish objective")
s = r(s, "            if (\n                float(hour.price) > max_price + TOLERANCE\n                and float(decision.paid_energy_kwh) > TOLERANCE\n            ):\n", "            if (\n                self.settings.planner_mode != PLANNER_MODE_SOLAR_ONLY\n                and float(hour.price) > max_price + TOLERANCE\n                and float(decision.paid_energy_kwh) > TOLERANCE\n            ):\n", "final price validation")
p.write_text(s)

p = Path("custom_components/ev_planner/core/ev_planner.py")
s = p.read_text()
s = r(s, "    CONF_ENTITY_PLANNER_MODE,\n    CONF_ENTITY_PRICES,\n", "    CONF_ENTITY_PLANNER_MODE,\n    CONF_ENTITY_PV_ROUNDING,\n    CONF_ENTITY_PRICES,\n", "controller imports")
s = r(s, "    DEFAULT_ENTITY_PLANNER_MODE,\n    DEFAULT_ENTITY_PRICES,\n", "    DEFAULT_ENTITY_PLANNER_MODE,\n    DEFAULT_ENTITY_PV_ROUNDING,\n    DEFAULT_ENTITY_PRICES,\n", "controller defaults")
s = r(s, "            \"planner_mode\": self.config.get(\n                CONF_ENTITY_PLANNER_MODE,\n                DEFAULT_ENTITY_PLANNER_MODE,\n            ),\n            \"solar_enabled\": self.config.get(\n", "            \"planner_mode\": self.config.get(\n                CONF_ENTITY_PLANNER_MODE,\n                DEFAULT_ENTITY_PLANNER_MODE,\n            ),\n            \"pv_rounding\": self.config.get(\n                CONF_ENTITY_PV_ROUNDING,\n                DEFAULT_ENTITY_PV_ROUNDING,\n            ),\n            \"solar_enabled\": self.config.get(\n", "controller entities")
s = r(s, "        # ------------------------------------------------------------------\n        # Fasewisselingen\n        # ------------------------------------------------------------------\n", "        # ------------------------------------------------------------------\n        # Planner mode\n        # ------------------------------------------------------------------\n\n        planner_mode = self.hass.get_state(self.entities[\"planner_mode\"])\n        if planner_mode not in (\"Normaal laden\", \"Alleen zonneladen\"):\n            self.logger.warning(f\"Ongeldige planner mode: {planner_mode}\")\n            return None\n\n        # ------------------------------------------------------------------\n        # PV-laadstroom afronding\n        # ------------------------------------------------------------------\n\n        pv_rounding = self.hass.get_state(self.entities[\"pv_rounding\"])\n        if pv_rounding not in (\n            \"Naar beneden — geen netenergie\",\n            \"Naar boven — kleine netaanvulling toegestaan\",\n        ):\n            self.logger.warning(f\"Ongeldige PV-afronding: {pv_rounding}\")\n            return None\n\n        # ------------------------------------------------------------------\n        # Fasewisselingen\n        # ------------------------------------------------------------------\n", "controller mode")
s = r(s, "                min_pv_kwh=min_pv_kwh,\n                solar_is_free=True,\n                max_charge_power_kw=self.max_charge_power_kw,\n", "                min_pv_kwh=min_pv_kwh,\n                solar_is_free=True,\n                max_charge_power_kw=self.max_charge_power_kw,\n                planner_mode=planner_mode,\n                pv_rounding=pv_rounding,\n", "controller settings")
p.write_text(s)

p = Path("tests/test_config_flow.py")
s = p.read_text()
s = r(s, "    CONF_ENTITY_PLANNER_MODE,\n    CONF_ENTITY_PRICES,\n", "    CONF_ENTITY_PLANNER_MODE,\n    CONF_ENTITY_PV_ROUNDING,\n    CONF_ENTITY_PRICES,\n", "test imports")
s = r(s, "        CONF_ENTITY_PLANNER_MODE: \"input_select.ev_planner_mode\",\n        CONF_ENTITY_PRICES", "        CONF_ENTITY_PLANNER_MODE: \"input_select.ev_planner_mode\",\n        CONF_ENTITY_PV_ROUNDING: \"input_select.ev_pv_afronding\",\n        CONF_ENTITY_PRICES", "test config")
p.write_text(s)

p = Path("tests/test_core.py")
s = p.read_text()
s += '''\n\ndef test_normal_mode_ignores_min_pv_threshold():\n    now = datetime.now(timezone.utc)\n    start = now.replace(minute=0, second=0, microsecond=0) + timedelta(hours=1)\n    plan = EVPlanner(\n        PriceData(hours=[make_hour(start, price=0.50)]),\n        SolcastData(hours=[make_hour(start, pv=0.50)]),\n        PlannerSettings(0.50, start + timedelta(hours=1), 0.0, min_pv_kwh=1.0, planner_mode=\"Normaal laden\"),\n        DummyLogger(),\n    ).create_plan()\n    assert plan.complete\n    assert plan.free_energy_kwh > 0.49\n    assert plan.paid_energy_kwh == pytest.approx(0.0, abs=1e-6)\n\n\ndef _solar_plan(pv, rounding):\n    now = datetime.now(timezone.utc)\n    start = now.replace(minute=0, second=0, microsecond=0) + timedelta(hours=1)\n    return EVPlanner(\n        PriceData(hours=[make_hour(start, price=0.50)]),\n        SolcastData(hours=[make_hour(start, pv=pv)]),\n        PlannerSettings(1.0, start + timedelta(hours=1), 0.0, max_phase_switches=8, planner_mode=\"Alleen zonneladen\", pv_rounding=rounding),\n        DummyLogger(),\n    ).create_plan()\n\n\ndef test_solar_only_round_down():\n    decision = _solar_plan(2.10, \"Naar beneden — geen netenergie\").decisions[0]\n    assert decision.charge_current_a == 9\n    assert decision.paid_energy_kwh == pytest.approx(0.0, abs=1e-6)\n\n\ndef test_solar_only_round_up_allows_grid_supplement():\n    plan = _solar_plan(2.10, \"Naar boven — kleine netaanvulling toegestaan\")\n    decision = plan.decisions[0]\n    assert decision.charge_current_a == 10\n    assert decision.paid_energy_kwh > 0.0\n    assert plan.complete\n\n\ndef test_solar_only_ignores_max_price_for_rounding_supplement():\n    plan = _solar_plan(2.10, \"Naar boven — kleine netaanvulling toegestaan\")\n    assert plan.paid_energy_kwh > 0.0\n\n\ndef test_solar_only_below_six_ampere_does_not_charge():\n    plan = _solar_plan(1.00, \"Naar boven — kleine netaanvulling toegestaan\")\n    assert not plan.complete\n    assert plan.energy_planned_kwh == pytest.approx(0.0, abs=1e-6)\n'''
p.write_text(s)
