update:
  name: Update
  description: Voert één EV Planner update uit.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:

create_plan:
  name: Nieuwe planning
  description: Maakt een nieuwe EV laadplanning.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:

replan:
  name: Opnieuw plannen
  description: Verwijdert de huidige planning en maakt direct een nieuwe.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:

clear_plan:
  name: Planning wissen
  description: Wist de huidige EV laadplanning.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:

status:
  name: Status
  description: Retourneert de actuele plannerstatus.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:

dashboard:
  name: Dashboarddata
  description: Retourneert de actuele plannerdata.
  fields:
    config_entry_id:
      name: Configuratie-entry
      description: De ID van de EV Charge Planner-configuratie.
      required: true
      selector:
        config_entry:
